-- ============================================================
-- TALLY LOCATION / PARTY LEDGER MASTER IMPORT SCRIPT
-- Database: u435643473_reqisition
-- 100% Name & Spelling Parity with Tally Master.xlsx (Total: 45 Locations)
-- ============================================================

USE u435643473_reqisition;

INSERT INTO `locations` (`code`, `name`, `tally_ledger_name`, `tally_ledger_code`, `status`, `created_at`) VALUES
('LOC-001', 'ACCOUNT OFFICE', 'ACCOUNT OFFICE', 'LED-001', 'ACTIVE', NOW()),
('LOC-002', 'ADARSH STEEL TRADERS', 'ADARSH STEEL TRADERS', 'LED-002', 'ACTIVE', NOW()),
('LOC-003', 'ANNA KESHTRA', 'ANNA KESHTRA', 'LED-003', 'ACTIVE', NOW()),
('LOC-004', 'BIG PANDAL', 'BIG PANDAL', 'LED-004', 'ACTIVE', NOW()),
('LOC-005', 'CNC MACHINE', 'CNC MACHINE', 'LED-005', 'ACTIVE', NOW()),
('LOC-006', 'CRYSTA 5919', 'CRYSTA 5919', 'LED-006', 'ACTIVE', NOW()),
('LOC-007', 'CRYSTA 7769', 'CRYSTA 7769', 'LED-007', 'ACTIVE', NOW()),
('LOC-008', 'DG 82.5 KV', 'DG 82.5 KV', 'LED-008', 'ACTIVE', NOW()),
('LOC-009', 'DG SET 400 KVA', 'DG SET 400 KVA', 'LED-009', 'ACTIVE', NOW()),
('LOC-010', 'DG SET 62.5 KVA NEW', 'DG SET 62.5 KVA NEW', 'LED-010', 'ACTIVE', NOW()),
('LOC-011', 'DHARAMSHALA MAINTENANCE', 'DHARAMSHALA MAINTENANCE', 'LED-011', 'ACTIVE', NOW()),
('LOC-012', 'GAUSHALA HATHKARGA', 'GAUSHALA HATHKARGA', 'LED-012', 'ACTIVE', NOW()),
('LOC-013', 'GAUSHALA STORE', 'GAUSHALA STORE', 'LED-013', 'ACTIVE', NOW()),
('LOC-014', 'GUNAYATAN GAUSHALA', 'GUNAYATAN GAUSHALA', 'LED-014', 'ACTIVE', NOW()),
('LOC-015', 'HYDRA ACE', 'HYDRA ACE', 'LED-015', 'ACTIVE', NOW()),
('LOC-016', 'HYDRA OLD', 'HYDRA OLD', 'LED-016', 'ACTIVE', NOW()),
('LOC-017', 'INNOVA ( MP342F 5327 )', 'INNOVA ( MP342F 5327 )', 'LED-017', 'ACTIVE', NOW()),
('LOC-018', 'IT WORK', 'IT WORK', 'LED-018', 'ACTIVE', NOW()),
('LOC-019', 'JCB GUNAYATAN', 'JCB GUNAYATAN', 'LED-019', 'ACTIVE', NOW()),
('LOC-020', 'JH11AN 9713 YODHA', 'JH11AN 9713 YODHA', 'LED-020', 'ACTIVE', NOW()),
('LOC-021', 'MAHAVIR ELECTRIC AND STATIONERY', 'MAHAVIR ELECTRIC AND STATIONERY', 'LED-021', 'ACTIVE', NOW()),
('LOC-022', 'MAIN GATE', 'MAIN GATE', 'LED-022', 'ACTIVE', NOW()),
('LOC-023', 'MAIN OFFICE', 'MAIN OFFICE', 'LED-023', 'ACTIVE', NOW()),
('LOC-024', 'MANDIRJI', 'MANDIRJI', 'LED-024', 'ACTIVE', NOW()),
('LOC-025', 'MISCELLANEOUS', 'MISCELLANEOUS', 'LED-025', 'ACTIVE', NOW()),
('LOC-026', 'MIXTURE MACHINE', 'MIXTURE MACHINE', 'LED-026', 'ACTIVE', NOW()),
('LOC-027', 'MODI BHAWAN', 'MODI BHAWAN', 'LED-027', 'ACTIVE', NOW()),
('LOC-028', 'M. P. BHAWAN', 'M. P. BHAWAN', 'LED-028', 'ACTIVE', NOW()),
('LOC-029', 'M.T.BHAWAN', 'M.T.BHAWAN', 'LED-029', 'ACTIVE', NOW()),
('LOC-030', 'PARVACHAN HALL', 'PARVACHAN HALL', 'LED-030', 'ACTIVE', NOW()),
('LOC-031', 'PAWAN DHAM ( MODI BHAWAN )', 'PAWAN DHAM ( MODI BHAWAN )', 'LED-031', 'ACTIVE', NOW()),
('LOC-032', 'ROAD ROLLER', 'ROAD ROLLER', 'LED-032', 'ACTIVE', NOW()),
('LOC-033', 'SADHNA BASTI', 'SADHNA BASTI', 'LED-033', 'ACTIVE', NOW()),
('LOC-034', 'SAHASTRAKUT JINALAYA', 'SAHASTRAKUT JINALAYA', 'LED-034', 'ACTIVE', NOW()),
('LOC-035', 'SANT NIWAS', 'SANT NIWAS', 'LED-035', 'ACTIVE', NOW()),
('LOC-036', 'SEVAYATAN', 'SEVAYATAN', 'LED-036', 'ACTIVE', NOW()),
('LOC-037', 'SHIKHARJEE CONTINENTAL HOTEL ( GUNAYATAN)', 'SHIKHARJEE CONTINENTAL HOTEL ( GUNAYATAN)', 'LED-037', 'ACTIVE', NOW()),
('LOC-038', 'SPLITTER MACHINE', 'SPLITTER MACHINE', 'LED-038', 'ACTIVE', NOW()),
('LOC-039', 'TOOLS GODAM', 'TOOLS GODAM', 'LED-039', 'ACTIVE', NOW()),
('LOC-040', 'TRACTOR 01', 'TRACTOR 01', 'LED-040', 'ACTIVE', NOW()),
('LOC-041', 'TRACTOR 02', 'TRACTOR 02', 'LED-041', 'ACTIVE', NOW()),
('LOC-042', 'TYAGI VARTI', 'TYAGI VARTI', 'LED-042', 'ACTIVE', NOW()),
('LOC-043', 'UTILITY 2', 'UTILITY 2', 'LED-043', 'ACTIVE', NOW()),
('LOC-044', 'UTILITY BUILDING  1', 'UTILITY BUILDING  1', 'LED-044', 'ACTIVE', NOW()),
('LOC-045', 'WINGER JH028D- 4110', 'WINGER JH028D- 4110', 'LED-045', 'ACTIVE', NOW())
ON DUPLICATE KEY UPDATE 
    `name` = VALUES(`name`),
    `tally_ledger_name` = VALUES(`tally_ledger_name`),
    `tally_ledger_code` = VALUES(`tally_ledger_code`),
    `status` = 'ACTIVE',
    `updated_at` = NOW();
